; Generated by img2asm.py
; Each INT 10h / AH=06h call fills a rectangle with a background color.
; Assembled with MASM/TASM for DOS / DOSBox.

.model small
.stack 100h
.data
    msg db 'Player1 Wins!$'
    msg2 db 'Like a true Master Mind$'
    
    msg3 db '[SPACE] RESTART$'
    msg4 db '[ESC]      QUIT$'

    stat1 db 'Tries: $'
    stat2 db 'Exact: $'
    stat3 db 'Mispl: $'
.code

    ; Set up data segment
    mov ax, @data
    mov ds, ax

    ; Set video mode 3 (80x25 color text)
    mov ah, 00h
    mov al, 03h
    int 10h

    ; Disable blink so all 16 colors work as backgrounds
    mov ax, 1003h
    mov bx, 0000h
    int 10h

    ; --- Pixel data (one INT 10h per color run) ---

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00000h   ; row=0, col=0
    mov dx, 0004Fh   ; row=0, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00100h   ; row=1, col=0
    mov dx, 0010Fh   ; row=1, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00110h   ; row=1, col=16
    mov dx, 00115h   ; row=1, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00116h   ; row=1, col=22
    mov dx, 00127h   ; row=1, col=39
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00128h   ; row=1, col=40
    mov dx, 0012Dh   ; row=1, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0012Eh   ; row=1, col=46
    mov dx, 0014Fh   ; row=1, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00200h   ; row=2, col=0
    mov dx, 0020Dh   ; row=2, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0020Eh   ; row=2, col=14
    mov dx, 0020Fh   ; row=2, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00210h   ; row=2, col=16
    mov dx, 00215h   ; row=2, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00216h   ; row=2, col=22
    mov dx, 00217h   ; row=2, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00218h   ; row=2, col=24
    mov dx, 00225h   ; row=2, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00226h   ; row=2, col=38
    mov dx, 00227h   ; row=2, col=39
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00228h   ; row=2, col=40
    mov dx, 0022Dh   ; row=2, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0022Eh   ; row=2, col=46
    mov dx, 0022Fh   ; row=2, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00230h   ; row=2, col=48
    mov dx, 0024Fh   ; row=2, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00300h   ; row=3, col=0
    mov dx, 0030Bh   ; row=3, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0030Ch   ; row=3, col=12
    mov dx, 0030Dh   ; row=3, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0030Eh   ; row=3, col=14
    mov dx, 00317h   ; row=3, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00318h   ; row=3, col=24
    mov dx, 00319h   ; row=3, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0031Ah   ; row=3, col=26
    mov dx, 00323h   ; row=3, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00324h   ; row=3, col=36
    mov dx, 00325h   ; row=3, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00326h   ; row=3, col=38
    mov dx, 0032Fh   ; row=3, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00330h   ; row=3, col=48
    mov dx, 00331h   ; row=3, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00332h   ; row=3, col=50
    mov dx, 0034Fh   ; row=3, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00400h   ; row=4, col=0
    mov dx, 00409h   ; row=4, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0040Ah   ; row=4, col=10
    mov dx, 0040Bh   ; row=4, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0040Ch   ; row=4, col=12
    mov dx, 00419h   ; row=4, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0041Ah   ; row=4, col=26
    mov dx, 00423h   ; row=4, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00424h   ; row=4, col=36
    mov dx, 00431h   ; row=4, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00432h   ; row=4, col=50
    mov dx, 00433h   ; row=4, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00434h   ; row=4, col=52
    mov dx, 0044Fh   ; row=4, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00500h   ; row=5, col=0
    mov dx, 00509h   ; row=5, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0050Ah   ; row=5, col=10
    mov dx, 0050Bh   ; row=5, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0050Ch   ; row=5, col=12
    mov dx, 00519h   ; row=5, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0051Ah   ; row=5, col=26
    mov dx, 0051Bh   ; row=5, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0051Ch   ; row=5, col=28
    mov dx, 0051Dh   ; row=5, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0051Eh   ; row=5, col=30
    mov dx, 0051Fh   ; row=5, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00520h   ; row=5, col=32
    mov dx, 00521h   ; row=5, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 00522h   ; row=5, col=34
    mov dx, 00523h   ; row=5, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00524h   ; row=5, col=36
    mov dx, 00531h   ; row=5, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00532h   ; row=5, col=50
    mov dx, 00533h   ; row=5, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00534h   ; row=5, col=52
    mov dx, 0054Fh   ; row=5, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00600h   ; row=6, col=0
    mov dx, 00609h   ; row=6, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0060Ah   ; row=6, col=10
    mov dx, 0060Bh   ; row=6, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0060Ch   ; row=6, col=12
    mov dx, 00619h   ; row=6, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0061Ah   ; row=6, col=26
    mov dx, 0061Bh   ; row=6, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0061Ch   ; row=6, col=28
    mov dx, 0061Dh   ; row=6, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0061Eh   ; row=6, col=30
    mov dx, 0061Fh   ; row=6, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00620h   ; row=6, col=32
    mov dx, 00621h   ; row=6, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 00622h   ; row=6, col=34
    mov dx, 00623h   ; row=6, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00624h   ; row=6, col=36
    mov dx, 00631h   ; row=6, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00632h   ; row=6, col=50
    mov dx, 00633h   ; row=6, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00634h   ; row=6, col=52
    mov dx, 0064Fh   ; row=6, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00700h   ; row=7, col=0
    mov dx, 00707h   ; row=7, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00708h   ; row=7, col=8
    mov dx, 00715h   ; row=7, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00716h   ; row=7, col=22
    mov dx, 00725h   ; row=7, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00726h   ; row=7, col=38
    mov dx, 00731h   ; row=7, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00732h   ; row=7, col=50
    mov dx, 0074Fh   ; row=7, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00800h   ; row=8, col=0
    mov dx, 00803h   ; row=8, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00804h   ; row=8, col=4
    mov dx, 00805h   ; row=8, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00806h   ; row=8, col=6
    mov dx, 00807h   ; row=8, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00808h   ; row=8, col=8
    mov dx, 00815h   ; row=8, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00816h   ; row=8, col=22
    mov dx, 00817h   ; row=8, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00818h   ; row=8, col=24
    mov dx, 00823h   ; row=8, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00824h   ; row=8, col=36
    mov dx, 00825h   ; row=8, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00826h   ; row=8, col=38
    mov dx, 00831h   ; row=8, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00832h   ; row=8, col=50
    mov dx, 00833h   ; row=8, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00834h   ; row=8, col=52
    mov dx, 00835h   ; row=8, col=53
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00836h   ; row=8, col=54
    mov dx, 00839h   ; row=8, col=57
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0083Ah   ; row=8, col=58
    mov dx, 0084Fh   ; row=8, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00900h   ; row=9, col=0
    mov dx, 00903h   ; row=9, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00904h   ; row=9, col=4
    mov dx, 00907h   ; row=9, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00908h   ; row=9, col=8
    mov dx, 00915h   ; row=9, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00916h   ; row=9, col=22
    mov dx, 00917h   ; row=9, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00918h   ; row=9, col=24
    mov dx, 00923h   ; row=9, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00924h   ; row=9, col=36
    mov dx, 00925h   ; row=9, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00926h   ; row=9, col=38
    mov dx, 00931h   ; row=9, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00932h   ; row=9, col=50
    mov dx, 00935h   ; row=9, col=53
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00936h   ; row=9, col=54
    mov dx, 0094Fh   ; row=9, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00A00h   ; row=10, col=0
    mov dx, 00A05h   ; row=10, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00A06h   ; row=10, col=6
    mov dx, 00A07h   ; row=10, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00A08h   ; row=10, col=8
    mov dx, 00A15h   ; row=10, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00A16h   ; row=10, col=22
    mov dx, 00A25h   ; row=10, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00A26h   ; row=10, col=38
    mov dx, 00A31h   ; row=10, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00A32h   ; row=10, col=50
    mov dx, 00A33h   ; row=10, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00A34h   ; row=10, col=52
    mov dx, 00A4Fh   ; row=10, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B00h   ; row=11, col=0
    mov dx, 00B07h   ; row=11, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B08h   ; row=11, col=8
    mov dx, 00B0Bh   ; row=11, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B0Ch   ; row=11, col=12
    mov dx, 00B0Dh   ; row=11, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B0Eh   ; row=11, col=14
    mov dx, 00B15h   ; row=11, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B16h   ; row=11, col=22
    mov dx, 00B17h   ; row=11, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B18h   ; row=11, col=24
    mov dx, 00B23h   ; row=11, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B24h   ; row=11, col=36
    mov dx, 00B25h   ; row=11, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B26h   ; row=11, col=38
    mov dx, 00B2Dh   ; row=11, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B2Eh   ; row=11, col=46
    mov dx, 00B2Fh   ; row=11, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B30h   ; row=11, col=48
    mov dx, 00B31h   ; row=11, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B32h   ; row=11, col=50
    mov dx, 00B39h   ; row=11, col=57
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B3Ah   ; row=11, col=58
    mov dx, 00B4Fh   ; row=11, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C00h   ; row=12, col=0
    mov dx, 00C05h   ; row=12, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C06h   ; row=12, col=6
    mov dx, 00C07h   ; row=12, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C08h   ; row=12, col=8
    mov dx, 00C15h   ; row=12, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C16h   ; row=12, col=22
    mov dx, 00C17h   ; row=12, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C18h   ; row=12, col=24
    mov dx, 00C23h   ; row=12, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C24h   ; row=12, col=36
    mov dx, 00C25h   ; row=12, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C26h   ; row=12, col=38
    mov dx, 00C31h   ; row=12, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C32h   ; row=12, col=50
    mov dx, 00C33h   ; row=12, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C34h   ; row=12, col=52
    mov dx, 00C4Fh   ; row=12, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D00h   ; row=13, col=0
    mov dx, 00D07h   ; row=13, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D08h   ; row=13, col=8
    mov dx, 00D09h   ; row=13, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 00D0Ah   ; row=13, col=10
    mov dx, 00D0Fh   ; row=13, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D10h   ; row=13, col=16
    mov dx, 00D15h   ; row=13, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D16h   ; row=13, col=22
    mov dx, 00D25h   ; row=13, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D26h   ; row=13, col=38
    mov dx, 00D33h   ; row=13, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D34h   ; row=13, col=52
    mov dx, 00D4Fh   ; row=13, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E00h   ; row=14, col=0
    mov dx, 00E09h   ; row=14, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 00E0Ah   ; row=14, col=10
    mov dx, 00E0Bh   ; row=14, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 00E0Ch   ; row=14, col=12
    mov dx, 00E0Dh   ; row=14, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 00E0Eh   ; row=14, col=14
    mov dx, 00E0Fh   ; row=14, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E10h   ; row=14, col=16
    mov dx, 00E17h   ; row=14, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00E18h   ; row=14, col=24
    mov dx, 00E23h   ; row=14, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E24h   ; row=14, col=36
    mov dx, 00E31h   ; row=14, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00E32h   ; row=14, col=50
    mov dx, 00E33h   ; row=14, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E34h   ; row=14, col=52
    mov dx, 00E4Fh   ; row=14, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F00h   ; row=15, col=0
    mov dx, 00F03h   ; row=15, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 00F04h   ; row=15, col=4
    mov dx, 00F0Bh   ; row=15, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 00F0Ch   ; row=15, col=12
    mov dx, 00F0Dh   ; row=15, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 00F0Eh   ; row=15, col=14
    mov dx, 00F0Fh   ; row=15, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F10h   ; row=15, col=16
    mov dx, 00F11h   ; row=15, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F12h   ; row=15, col=18
    mov dx, 00F19h   ; row=15, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F1Ah   ; row=15, col=26
    mov dx, 00F1Bh   ; row=15, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F1Ch   ; row=15, col=28
    mov dx, 00F1Dh   ; row=15, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F1Eh   ; row=15, col=30
    mov dx, 00F1Fh   ; row=15, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F20h   ; row=15, col=32
    mov dx, 00F21h   ; row=15, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F22h   ; row=15, col=34
    mov dx, 00F23h   ; row=15, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F24h   ; row=15, col=36
    mov dx, 00F2Fh   ; row=15, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F30h   ; row=15, col=48
    mov dx, 00F31h   ; row=15, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F32h   ; row=15, col=50
    mov dx, 00F4Fh   ; row=15, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01000h   ; row=16, col=0
    mov dx, 01001h   ; row=16, col=1
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01002h   ; row=16, col=2
    mov dx, 01003h   ; row=16, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 01004h   ; row=16, col=4
    mov dx, 01007h   ; row=16, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01008h   ; row=16, col=8
    mov dx, 0100Bh   ; row=16, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 0100Ch   ; row=16, col=12
    mov dx, 0100Fh   ; row=16, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01010h   ; row=16, col=16
    mov dx, 01011h   ; row=16, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01012h   ; row=16, col=18
    mov dx, 01015h   ; row=16, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01016h   ; row=16, col=22
    mov dx, 01019h   ; row=16, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0101Ah   ; row=16, col=26
    mov dx, 01023h   ; row=16, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01024h   ; row=16, col=36
    mov dx, 0102Bh   ; row=16, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0102Ch   ; row=16, col=44
    mov dx, 01033h   ; row=16, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01034h   ; row=16, col=52
    mov dx, 0104Fh   ; row=16, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01100h   ; row=17, col=0
    mov dx, 01101h   ; row=17, col=1
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01102h   ; row=17, col=2
    mov dx, 01105h   ; row=17, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 01106h   ; row=17, col=6
    mov dx, 01109h   ; row=17, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 0110Ah   ; row=17, col=10
    mov dx, 0110Bh   ; row=17, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 0110Ch   ; row=17, col=12
    mov dx, 0110Fh   ; row=17, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01110h   ; row=17, col=16
    mov dx, 01111h   ; row=17, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01112h   ; row=17, col=18
    mov dx, 01131h   ; row=17, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01132h   ; row=17, col=50
    mov dx, 01133h   ; row=17, col=51
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01134h   ; row=17, col=52
    mov dx, 0114Fh   ; row=17, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01200h   ; row=18, col=0
    mov dx, 01201h   ; row=18, col=1
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01202h   ; row=18, col=2
    mov dx, 01203h   ; row=18, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 01204h   ; row=18, col=4
    mov dx, 01205h   ; row=18, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01206h   ; row=18, col=6
    mov dx, 01209h   ; row=18, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 0120Ah   ; row=18, col=10
    mov dx, 0120Fh   ; row=18, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01210h   ; row=18, col=16
    mov dx, 01211h   ; row=18, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01212h   ; row=18, col=18
    mov dx, 0122Fh   ; row=18, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01230h   ; row=18, col=48
    mov dx, 01231h   ; row=18, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01232h   ; row=18, col=50
    mov dx, 0124Fh   ; row=18, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01300h   ; row=19, col=0
    mov dx, 01303h   ; row=19, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01304h   ; row=19, col=4
    mov dx, 01305h   ; row=19, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0E0h
    mov cx, 01306h   ; row=19, col=6
    mov dx, 0130Dh   ; row=19, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 0130Eh   ; row=19, col=14
    mov dx, 0130Fh   ; row=19, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01310h   ; row=19, col=16
    mov dx, 01311h   ; row=19, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01312h   ; row=19, col=18
    mov dx, 0132Dh   ; row=19, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0132Eh   ; row=19, col=46
    mov dx, 0132Fh   ; row=19, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01330h   ; row=19, col=48
    mov dx, 0134Fh   ; row=19, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01400h   ; row=20, col=0
    mov dx, 01405h   ; row=20, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 060h
    mov cx, 01406h   ; row=20, col=6
    mov dx, 0140Dh   ; row=20, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0140Eh   ; row=20, col=14
    mov dx, 0140Fh   ; row=20, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01410h   ; row=20, col=16
    mov dx, 01411h   ; row=20, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01412h   ; row=20, col=18
    mov dx, 0142Dh   ; row=20, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0142Eh   ; row=20, col=46
    mov dx, 0142Fh   ; row=20, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01430h   ; row=20, col=48
    mov dx, 0144Fh   ; row=20, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01500h   ; row=21, col=0
    mov dx, 0150Fh   ; row=21, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01510h   ; row=21, col=16
    mov dx, 01511h   ; row=21, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01512h   ; row=21, col=18
    mov dx, 01517h   ; row=21, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01518h   ; row=21, col=24
    mov dx, 01527h   ; row=21, col=39
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01528h   ; row=21, col=40
    mov dx, 0152Dh   ; row=21, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0152Eh   ; row=21, col=46
    mov dx, 0152Fh   ; row=21, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01530h   ; row=21, col=48
    mov dx, 0154Fh   ; row=21, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01600h   ; row=22, col=0
    mov dx, 0160Fh   ; row=22, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01610h   ; row=22, col=16
    mov dx, 01611h   ; row=22, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01612h   ; row=22, col=18
    mov dx, 01615h   ; row=22, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01616h   ; row=22, col=22
    mov dx, 01617h   ; row=22, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01618h   ; row=22, col=24
    mov dx, 01627h   ; row=22, col=39
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01628h   ; row=22, col=40
    mov dx, 01629h   ; row=22, col=41
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0162Ah   ; row=22, col=42
    mov dx, 0162Dh   ; row=22, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0162Eh   ; row=22, col=46
    mov dx, 0162Fh   ; row=22, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01630h   ; row=22, col=48
    mov dx, 0164Fh   ; row=22, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01700h   ; row=23, col=0
    mov dx, 01711h   ; row=23, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01712h   ; row=23, col=18
    mov dx, 01715h   ; row=23, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01716h   ; row=23, col=22
    mov dx, 01729h   ; row=23, col=41
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0172Ah   ; row=23, col=42
    mov dx, 0172Dh   ; row=23, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0172Eh   ; row=23, col=46
    mov dx, 0174Fh   ; row=23, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01800h   ; row=24, col=0
    mov dx, 0184Fh   ; row=24, col=79
    int 10h

    mov ah, 02h
    mov bh, 00h
    mov dh, 06h     ; row 6
    mov dl, 3Ch     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, stat1
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 08h     ; row 8
    mov dl, 3Ch     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, stat2
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 0Ah     ; row 10
    mov dl, 3Ch     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, stat3
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 0Fh     ; row 15
    mov dl, 3Bh     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 10h     ; row 16
    mov dl, 36h     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg2
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 12h     ; row 18
    mov dl, 3Ah     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg3
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 13h     ; row 19
    mov dl, 3Ah     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg4
    int 21h    

    ; Wait for keypress then exit
    mov ah, 00h
    int 16h

    mov ax, 4C00h
    int 21h

END