; Generated by img2asm.py
; Each INT 10h / AH=06h call fills a rectangle with a background color.
; Assembled with MASM/TASM for DOS / DOSBox.

.model small
.stack 100h
.data
    msg db 'Player2 Wins!$'
    msg2 db 'You have out-mastered$'
    msg3 db 'the Mastermind$'

    msg4 db '[SPACE] RESTART$'
    msg5 db '[ESC]      QUIT$'

    stat1 db 'Tries: $'
    stat2 db 'Exact: $'
    stat3 db 'Mispl: $'
.code

    ; Set up data segment
    mov ax, @data
    mov ds, ax

    ; Set video mode 3 (80x25 color text)
    mov ah, 00h
    mov al, 03h
    int 10h

    ; Disable blink so all 16 colors work as backgrounds
    mov ax, 1003h
    mov bx, 0000h
    int 10h

    ; --- Pixel data (one INT 10h per color run) ---

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00000h   ; row=0, col=0
    mov dx, 0004Fh   ; row=0, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00100h   ; row=1, col=0
    mov dx, 0014Fh   ; row=1, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00200h   ; row=2, col=0
    mov dx, 0024Fh   ; row=2, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00300h   ; row=3, col=0
    mov dx, 0034Fh   ; row=3, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00400h   ; row=4, col=0
    mov dx, 0044Fh   ; row=4, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00500h   ; row=5, col=0
    mov dx, 00509h   ; row=5, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0050Ah   ; row=5, col=10
    mov dx, 0050Fh   ; row=5, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00510h   ; row=5, col=16
    mov dx, 00523h   ; row=5, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00524h   ; row=5, col=36
    mov dx, 00529h   ; row=5, col=41
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0052Ah   ; row=5, col=42
    mov dx, 0054Fh   ; row=5, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00600h   ; row=6, col=0
    mov dx, 00607h   ; row=6, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00608h   ; row=6, col=8
    mov dx, 00609h   ; row=6, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0060Ah   ; row=6, col=10
    mov dx, 0060Fh   ; row=6, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00610h   ; row=6, col=16
    mov dx, 00611h   ; row=6, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00612h   ; row=6, col=18
    mov dx, 00621h   ; row=6, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00622h   ; row=6, col=34
    mov dx, 00623h   ; row=6, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00624h   ; row=6, col=36
    mov dx, 00629h   ; row=6, col=41
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0062Ah   ; row=6, col=42
    mov dx, 0062Bh   ; row=6, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0062Ch   ; row=6, col=44
    mov dx, 0064Fh   ; row=6, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00700h   ; row=7, col=0
    mov dx, 00707h   ; row=7, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00708h   ; row=7, col=8
    mov dx, 00709h   ; row=7, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0070Ah   ; row=7, col=10
    mov dx, 00711h   ; row=7, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00712h   ; row=7, col=18
    mov dx, 00721h   ; row=7, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00722h   ; row=7, col=34
    mov dx, 00729h   ; row=7, col=41
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0072Ah   ; row=7, col=42
    mov dx, 0072Bh   ; row=7, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0072Ch   ; row=7, col=44
    mov dx, 0074Fh   ; row=7, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00800h   ; row=8, col=0
    mov dx, 00805h   ; row=8, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00806h   ; row=8, col=6
    mov dx, 00807h   ; row=8, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00808h   ; row=8, col=8
    mov dx, 00815h   ; row=8, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 00816h   ; row=8, col=22
    mov dx, 00817h   ; row=8, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00818h   ; row=8, col=24
    mov dx, 00819h   ; row=8, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0081Ah   ; row=8, col=26
    mov dx, 0081Bh   ; row=8, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0081Ch   ; row=8, col=28
    mov dx, 0081Dh   ; row=8, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0081Eh   ; row=8, col=30
    mov dx, 0081Fh   ; row=8, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00820h   ; row=8, col=32
    mov dx, 0082Bh   ; row=8, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0082Ch   ; row=8, col=44
    mov dx, 0082Dh   ; row=8, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0082Eh   ; row=8, col=46
    mov dx, 0084Fh   ; row=8, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00900h   ; row=9, col=0
    mov dx, 00905h   ; row=9, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00906h   ; row=9, col=6
    mov dx, 00907h   ; row=9, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00908h   ; row=9, col=8
    mov dx, 00915h   ; row=9, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 00916h   ; row=9, col=22
    mov dx, 00917h   ; row=9, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00918h   ; row=9, col=24
    mov dx, 00919h   ; row=9, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0091Ah   ; row=9, col=26
    mov dx, 0091Bh   ; row=9, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0091Ch   ; row=9, col=28
    mov dx, 0091Dh   ; row=9, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 070h
    mov cx, 0091Eh   ; row=9, col=30
    mov dx, 0091Fh   ; row=9, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00920h   ; row=9, col=32
    mov dx, 0092Bh   ; row=9, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0092Ch   ; row=9, col=44
    mov dx, 0092Dh   ; row=9, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0092Eh   ; row=9, col=46
    mov dx, 0094Fh   ; row=9, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00A00h   ; row=10, col=0
    mov dx, 00A03h   ; row=10, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00A04h   ; row=10, col=4
    mov dx, 00A2Bh   ; row=10, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00A2Ch   ; row=10, col=44
    mov dx, 00A2Dh   ; row=10, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00A2Eh   ; row=10, col=46
    mov dx, 00A31h   ; row=10, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00A32h   ; row=10, col=50
    mov dx, 00A35h   ; row=10, col=53
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00A36h   ; row=10, col=54
    mov dx, 00A4Fh   ; row=10, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B00h   ; row=11, col=0
    mov dx, 00B03h   ; row=11, col=3
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B04h   ; row=11, col=4
    mov dx, 00B07h   ; row=11, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B08h   ; row=11, col=8
    mov dx, 00B2Dh   ; row=11, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00B2Eh   ; row=11, col=46
    mov dx, 00B31h   ; row=11, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00B32h   ; row=11, col=50
    mov dx, 00B4Fh   ; row=11, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C00h   ; row=12, col=0
    mov dx, 00C09h   ; row=12, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C0Ah   ; row=12, col=10
    mov dx, 00C0Dh   ; row=12, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C0Eh   ; row=12, col=14
    mov dx, 00C13h   ; row=12, col=19
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C14h   ; row=12, col=20
    mov dx, 00C15h   ; row=12, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C16h   ; row=12, col=22
    mov dx, 00C19h   ; row=12, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C1Ah   ; row=12, col=26
    mov dx, 00C1Fh   ; row=12, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C20h   ; row=12, col=32
    mov dx, 00C21h   ; row=12, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C22h   ; row=12, col=34
    mov dx, 00C23h   ; row=12, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C24h   ; row=12, col=36
    mov dx, 00C25h   ; row=12, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00C26h   ; row=12, col=38
    mov dx, 00C29h   ; row=12, col=41
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00C2Ah   ; row=12, col=42
    mov dx, 00C4Fh   ; row=12, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D00h   ; row=13, col=0
    mov dx, 00D07h   ; row=13, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D08h   ; row=13, col=8
    mov dx, 00D09h   ; row=13, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D0Ah   ; row=13, col=10
    mov dx, 00D0Dh   ; row=13, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D0Eh   ; row=13, col=14
    mov dx, 00D13h   ; row=13, col=19
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D14h   ; row=13, col=20
    mov dx, 00D19h   ; row=13, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D1Ah   ; row=13, col=26
    mov dx, 00D1Fh   ; row=13, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D20h   ; row=13, col=32
    mov dx, 00D23h   ; row=13, col=35
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D24h   ; row=13, col=36
    mov dx, 00D25h   ; row=13, col=37
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D26h   ; row=13, col=38
    mov dx, 00D29h   ; row=13, col=41
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D2Ah   ; row=13, col=42
    mov dx, 00D2Dh   ; row=13, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00D2Eh   ; row=13, col=46
    mov dx, 00D35h   ; row=13, col=53
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00D36h   ; row=13, col=54
    mov dx, 00D4Fh   ; row=13, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E00h   ; row=14, col=0
    mov dx, 00E17h   ; row=14, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00E18h   ; row=14, col=24
    mov dx, 00E19h   ; row=14, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E1Ah   ; row=14, col=26
    mov dx, 00E1Fh   ; row=14, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00E20h   ; row=14, col=32
    mov dx, 00E21h   ; row=14, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E22h   ; row=14, col=34
    mov dx, 00E2Bh   ; row=14, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00E2Ch   ; row=14, col=44
    mov dx, 00E2Dh   ; row=14, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00E2Eh   ; row=14, col=46
    mov dx, 00E4Fh   ; row=14, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F00h   ; row=15, col=0
    mov dx, 00F05h   ; row=15, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F06h   ; row=15, col=6
    mov dx, 00F07h   ; row=15, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F08h   ; row=15, col=8
    mov dx, 00F09h   ; row=15, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F0Ah   ; row=15, col=10
    mov dx, 00F0Dh   ; row=15, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F0Eh   ; row=15, col=14
    mov dx, 00F17h   ; row=15, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F18h   ; row=15, col=24
    mov dx, 00F19h   ; row=15, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F1Ah   ; row=15, col=26
    mov dx, 00F1Fh   ; row=15, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F20h   ; row=15, col=32
    mov dx, 00F21h   ; row=15, col=33
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F22h   ; row=15, col=34
    mov dx, 00F2Bh   ; row=15, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 00F2Ch   ; row=15, col=44
    mov dx, 00F2Fh   ; row=15, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 00F30h   ; row=15, col=48
    mov dx, 00F4Fh   ; row=15, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01000h   ; row=16, col=0
    mov dx, 01005h   ; row=16, col=5
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01006h   ; row=16, col=6
    mov dx, 01009h   ; row=16, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0100Ah   ; row=16, col=10
    mov dx, 0100Dh   ; row=16, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0100Eh   ; row=16, col=14
    mov dx, 0100Fh   ; row=16, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01010h   ; row=16, col=16
    mov dx, 01017h   ; row=16, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01018h   ; row=16, col=24
    mov dx, 01019h   ; row=16, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0101Ah   ; row=16, col=26
    mov dx, 0101Dh   ; row=16, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0101Eh   ; row=16, col=30
    mov dx, 0101Fh   ; row=16, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01020h   ; row=16, col=32
    mov dx, 0102Bh   ; row=16, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0102Ch   ; row=16, col=44
    mov dx, 0102Dh   ; row=16, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0102Eh   ; row=16, col=46
    mov dx, 0102Fh   ; row=16, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01030h   ; row=16, col=48
    mov dx, 01031h   ; row=16, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01032h   ; row=16, col=50
    mov dx, 0104Fh   ; row=16, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01100h   ; row=17, col=0
    mov dx, 01107h   ; row=17, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01108h   ; row=17, col=8
    mov dx, 01109h   ; row=17, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0110Ah   ; row=17, col=10
    mov dx, 0110Fh   ; row=17, col=15
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01110h   ; row=17, col=16
    mov dx, 01111h   ; row=17, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01112h   ; row=17, col=18
    mov dx, 01117h   ; row=17, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01118h   ; row=17, col=24
    mov dx, 01119h   ; row=17, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0111Ah   ; row=17, col=26
    mov dx, 0111Dh   ; row=17, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0111Eh   ; row=17, col=30
    mov dx, 0111Fh   ; row=17, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01120h   ; row=17, col=32
    mov dx, 0112Bh   ; row=17, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0112Ch   ; row=17, col=44
    mov dx, 0112Dh   ; row=17, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0112Eh   ; row=17, col=46
    mov dx, 0112Fh   ; row=17, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01130h   ; row=17, col=48
    mov dx, 01131h   ; row=17, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01132h   ; row=17, col=50
    mov dx, 0114Fh   ; row=17, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01200h   ; row=18, col=0
    mov dx, 01207h   ; row=18, col=7
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01208h   ; row=18, col=8
    mov dx, 01209h   ; row=18, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0120Ah   ; row=18, col=10
    mov dx, 01211h   ; row=18, col=17
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01212h   ; row=18, col=18
    mov dx, 01213h   ; row=18, col=19
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01214h   ; row=18, col=20
    mov dx, 01217h   ; row=18, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01218h   ; row=18, col=24
    mov dx, 01219h   ; row=18, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0121Ah   ; row=18, col=26
    mov dx, 0121Dh   ; row=18, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0121Eh   ; row=18, col=30
    mov dx, 0121Fh   ; row=18, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01220h   ; row=18, col=32
    mov dx, 01227h   ; row=18, col=39
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01228h   ; row=18, col=40
    mov dx, 0122Bh   ; row=18, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0122Ch   ; row=18, col=44
    mov dx, 0122Fh   ; row=18, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01230h   ; row=18, col=48
    mov dx, 01231h   ; row=18, col=49
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01232h   ; row=18, col=50
    mov dx, 0124Fh   ; row=18, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01300h   ; row=19, col=0
    mov dx, 01309h   ; row=19, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0130Ah   ; row=19, col=10
    mov dx, 0130Bh   ; row=19, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0130Ch   ; row=19, col=12
    mov dx, 01313h   ; row=19, col=19
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01314h   ; row=19, col=20
    mov dx, 01315h   ; row=19, col=21
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01316h   ; row=19, col=22
    mov dx, 01317h   ; row=19, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01318h   ; row=19, col=24
    mov dx, 01319h   ; row=19, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0131Ah   ; row=19, col=26
    mov dx, 0131Bh   ; row=19, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0131Ch   ; row=19, col=28
    mov dx, 0131Dh   ; row=19, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0131Eh   ; row=19, col=30
    mov dx, 0131Fh   ; row=19, col=31
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01320h   ; row=19, col=32
    mov dx, 01327h   ; row=19, col=39
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01328h   ; row=19, col=40
    mov dx, 0132Dh   ; row=19, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0132Eh   ; row=19, col=46
    mov dx, 0132Fh   ; row=19, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01330h   ; row=19, col=48
    mov dx, 0134Fh   ; row=19, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01400h   ; row=20, col=0
    mov dx, 0140Bh   ; row=20, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0140Ch   ; row=20, col=12
    mov dx, 0140Dh   ; row=20, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0140Eh   ; row=20, col=14
    mov dx, 01417h   ; row=20, col=23
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 01418h   ; row=20, col=24
    mov dx, 01419h   ; row=20, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0141Ah   ; row=20, col=26
    mov dx, 0141Bh   ; row=20, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0141Ch   ; row=20, col=28
    mov dx, 0141Dh   ; row=20, col=29
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0141Eh   ; row=20, col=30
    mov dx, 0142Bh   ; row=20, col=43
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0142Ch   ; row=20, col=44
    mov dx, 0142Dh   ; row=20, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0142Eh   ; row=20, col=46
    mov dx, 0144Fh   ; row=20, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01500h   ; row=21, col=0
    mov dx, 0150Bh   ; row=21, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0150Ch   ; row=21, col=12
    mov dx, 0150Dh   ; row=21, col=13
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0150Eh   ; row=21, col=14
    mov dx, 01519h   ; row=21, col=25
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0151Ah   ; row=21, col=26
    mov dx, 0151Bh   ; row=21, col=27
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0151Ch   ; row=21, col=28
    mov dx, 0152Dh   ; row=21, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0152Eh   ; row=21, col=46
    mov dx, 0152Fh   ; row=21, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01530h   ; row=21, col=48
    mov dx, 0154Fh   ; row=21, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01600h   ; row=22, col=0
    mov dx, 01609h   ; row=22, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0160Ah   ; row=22, col=10
    mov dx, 0160Bh   ; row=22, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0160Ch   ; row=22, col=12
    mov dx, 0162Dh   ; row=22, col=45
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0162Eh   ; row=22, col=46
    mov dx, 0162Fh   ; row=22, col=47
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01630h   ; row=22, col=48
    mov dx, 0164Fh   ; row=22, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01700h   ; row=23, col=0
    mov dx, 01709h   ; row=23, col=9
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 000h
    mov cx, 0170Ah   ; row=23, col=10
    mov dx, 0170Bh   ; row=23, col=11
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 0170Ch   ; row=23, col=12
    mov dx, 0174Fh   ; row=23, col=79
    int 10h

    mov ah, 06h
    mov al, 00h
    mov bh, 0F0h
    mov cx, 01800h   ; row=24, col=0
    mov dx, 0184Fh   ; row=24, col=79
    int 10h

    mov ah, 02h
    mov bh, 00h
    mov dh, 06h     ; row 6
    mov dl, 3Ch     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, stat1
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 08h     ; row 8
    mov dl, 3Ch     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, stat2
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 0Ah     ; row 10
    mov dl, 3Ch     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, stat3
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 0Fh     ; row 15
    mov dl, 39h     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 10h     ; row 16
    mov dl, 35h     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg2
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 11h     ; row 17
    mov dl, 39h     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg3
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 13h     ; row 19
    mov dl, 39h     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg4
    int 21h

    mov ah, 02h
    mov bh, 00h
    mov dh, 14h     ; row 20
    mov dl, 39h     
    int 10h

    ; Print the string
    mov ah, 09h
    lea dx, msg5
    int 21h

    ; Wait for keypress then exit
    mov ah, 00h
    int 16h

    mov ax, 4C00h
    int 21h

END